# Generated by Django 4.2.4 on 2023-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('company_code', models.CharField(max_length=5, unique=True)),
                ('strength', models.PositiveBigIntegerField()),
                ('website', models.URLField()),
                ('created_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
