# Generated by Django 4.2.4 on 2023-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
