# Generated by Django 4.2.4 on 2023-09-06 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_options_alter_company_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Company code must be in the format XX99E or XX99N', regex='^[A-Z]{2}\\d{2}[EN]$')]),
        ),
    ]
